### PR TITLE
[RE-667] Docker engine misconfigured

### PR DESCRIPTION
**Pull request by thegreenbear**
Fixed bug in Kubespray preventing the systemd config for docker to be provisioned.

### CODE REVIEW

**Comment by thegreenbear** [comment]
If you're interested in the bug report:
https://github.com/kubernetes-sigs/kubespray/issues/6348

**Review by ghost — APPROVED** [review]

**Review by levsha — APPROVED** [review]

**Comment by thegreenbear** [comment]
@lukatera and @levsha , I pushed a new commit. Not sure if you want to review again or not?

**Comment by ghost** [comment]
> @lukatera and @levsha , I pushed a new commit. Not sure if you want to review again or not?

hmm, that last commit seems weird :D
this is basically equivalent to `ignore_errors: yes` which doesn't seem that nice of a solution

**Comment by thegreenbear** [comment]
> `ignore_errors`

That's exactly what it is. Maybe you'll have a better idea once you know the story.
- There's a handler restarting the service managing the unix socket used by dockerd
  On Fedora CoreOS, this restarts fails and leaves the service in a dead state. It was reproducible on two machines.
- The task right after is restarting the service managing dockerd. This one has a dependency on that socket.
  Restarting this service, actually restarts the socket as well. At least on the two nodes I've tested against.

So I don't see the point of this task restarting the socket service.
As it might be useful for other OS, I thought the best was to leave it there and move on in case of failure.
If you have a better idea, I take it!

**Review by levsha — APPROVED** [review]

**Comment by thegreenbear** [comment]
@lukatera , let me know what you think.

**Pull request closed without merging**
